version: "3"
volumes:
  pgdata:

services: 
  app:
    build: 
      context: .
      dockerfile: docker/dev/python/Dockerfile
    image: webapp:ohm_django
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: "python test_project/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    