version: "2"
volumes:
  pgdata:
  static_files:

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    volumes:
      - ./app:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    command: "gunicorn -w 4 --chdir test_project/ test_project.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - static_files:/static_files
    