version: "3"
volumes:
  pgdata:
  static_files:

services:
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - static_files:/static_files
      - ./docker/prod/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    
  app:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    image: webapp_production
    environment:
      - DJANGO_SETTINGS_MODULE=test_project.settings.prod
    volumes:
      - ./app:/app
      - static_files:/static_files
    ports:
      - 8000:8000
    command: 
      - "gunicorn -w 4 --chdir test_project/ test_project.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres